[theme]
primaryColor = "#F15A22"
backgroundColor = "#FAF7F3"
secondaryBackgroundColor = "#102A46"
textColor = "#26323F"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true